version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: selectunes
      POSTGRES_USER: selectunes
      POSTGRES_DB: selectunes
    dns: 8.8.8.8
  web:
    build: .
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "443:443"
